name: Java CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '11'
        java-package: 'jdk+fx'
    - name: Build with Gradle
      run: ./gradlew build
      env:
        VERSION_TYPE: "official"
        MICROSOFT_AUTH_ID: "6a3728d6-27a3-4180-99bb-479895b8f88e"
        MICROSOFT_AUTH_SECRET: "dR.50SWwVez4-PQOF2-e_2GHmC~4Xl-p4p"
        CURSEFORGE_API_KEY: "$2a$10$o8pygPrhvKBHuuh5imL2W.LCNFhB15zBYAExXx/TqTx/Z"
    - name: Get short SHA
      run: echo "SHORT_SHA=${GITHUB_SHA::7}" >> $GITHUB_ENV
    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: HMCL-${{ env.SHORT_SHA }}
        path: HMCL/build/libs
